.gitignore
Gemfile
J2ObjC.podspec

Inspired by the work done in https://github.com/goodow/j2objc but uses cocoapods facilities to download the release rather than shelling out. @tomball /cc @goodow

Add podspec

---

index.html

@tomball - first attempt on pull request for documentation

Questions section now points to StackOverflow

---

docs/Arrays.md

Here's a draft of the Arrays doc. Please review and let me know when it's suitable to pull.

Updated Arrays reference page.

---

docs/Required-Link-Flags.md

You can see the generated page [here](http://tomball.github.io/j2objc/docs/Required-Link-Flags.html) (ignore the screwed up menu on the left).

Rewrote link flags doc.

---

INSTALL
README.md

Following the suggestions in #666, this updates the build requirements as well as links to the mentioned tools.

Update build requirements and tool links

---

_includes/header.html
_posts/2016-03-17-default-methods.md

* Fix a typo
* Use a more appropriate header style
* Other minor edits (wrapping, monospaced texts, JavaScript updates)

Minor edits

---

jre_emul/Classes/java/lang/System.java
make/common.mk
make/fat_lib_macros.mk
scripts/sysroot_path.sh

Drop support for armv7s and add support for watchOS and armv7k, see https://groups.google.com/forum/#!topic/j2objc-discuss/IA85e_8rXg8

Add WatchOS support

---

.gitignore

Added .DS_Store files to the ignore list

Added ignore for Mac filesystem .DS_Store files

---

make/static_framework.mk

Hi,
I found out that there was already some work done (commit 01c8d7f2) on issue #752. I modified the mk script to reflect changes to the modulemap syntax and location. Xcode Version 7.3.1 (7D1014).

corrected modulemaps location and declaration

---

translator/src/main/java/com/google/devtools/j2objc/Options.java

Fixed classpath for aar files.

---

translator/src/main/java/com/google/devtools/j2objc/translate/MetadataWriter.java

Disregard warning in Xcode. Comes up occasionally.

Remove occasional Xcode warning

---

jre_emul/android/platform/libcore/ojluni/src/main/java/java/util/Collections.java

@tomball this is not tested yet (in the wild), just opening the PR. This still is sound

Use object to synchronizes instead of this

---

jre_emul/Classes/java/lang/System.java

Taken from https://android.googlesource.com/platform/libcore/+/nougat-release/ojluni/src/main/java/java/lang/System.java

Add missing inheritedChannel method

---

jre_emul/Classes/com/google/j2objc/net/ssl/IosSslSocket.m

I've found another minor issue with the ssl socket implementation: For wrapped sockets, we are using the inetaddress of the underlying socket for SSLSetPeerDomainName. This is problematic, as with wrapped sockets, the underlying (wrapped) socket might be connected to a different host than the upper (wrapper) socket. An example for this would be an http proxy that is secured with ssl and is used to access an https server.
This commit fixes this problem in a way that is similar to how the [Conscrypt SSL provider](https://github.com/google/conscrypt/blob/8ea8a56875cfb109d52b436b8ebc0d1ca8b8e5f8/common/src/main/java/org/conscrypt/AbstractConscryptSocket.java) does it.

Use correct hostname for wrapped ssl connections

---

jre_emul/android/platform/libcore/luni/src/main/java/javax/xml/datatype/FactoryFinder.java

Updating javax.xml.datatype.

---

jre_emul/android/platform/libcore/ojluni/src/main/java/java/security/interfaces/DSAParams.java
jre_emul/android/platform/libcore/ojluni/src/main/java/javax/crypto/interfaces/package.html
jre_emul/android/platform/libcore/ojluni/src/main/java/javax/crypto/spec/SecretKeySpec.java
jre_emul/android/platform/libcore/ojluni/src/main/java/javax/crypto/spec/package.html

Updating documentations for
- java.security.interfaces
- javax.crypto.interfaces
- javax.crypto.spec

Updated docs

---

jre_emul/android/platform/libcore/luni/src/main/java/org/w3c/dom/ls/LSSerializerFilter.java
jre_emul/android/platform/libcore/luni/src/main/java/org/w3c/dom/traversal/NodeFilter.java
jre_emul/android/platform/libcore/luni/src/main/java/org/w3c/dom/traversal/NodeIterator.java
jre_emul/android/platform/libcore/luni/src/main/java/org/xml/sax/HandlerBase.java
jre_emul/android/platform/libcore/luni/src/main/java/org/xml/sax/InputSource.java
jre_emul/android/platform/libcore/luni/src/main/java/org/xml/sax/SAXException.java
jre_emul/android/platform/libcore/luni/src/main/java/org/xml/sax/SAXParseException.java
jre_emul/android/platform/libcore/luni/src/main/java/org/xml/sax/ext/Attributes2Impl.java
jre_emul/android/platform/libcore/luni/src/main/java/org/xml/sax/ext/Locator2Impl.java
jre_emul/android/platform/libcore/luni/src/main/java/org/xml/sax/helpers/AttributesImpl.java
jre_emul/android/platform/libcore/luni/src/main/java/org/xml/sax/helpers/DefaultHandler.java
jre_emul/android/platform/libcore/luni/src/main/java/org/xml/sax/helpers/LocatorImpl.java
jre_emul/android/platform/libcore/luni/src/main/java/org/xml/sax/helpers/NamespaceSupport.java
jre_emul/android/platform/libcore/luni/src/main/java/org/xml/sax/helpers/ParserAdapter.java
jre_emul/android/platform/libcore/luni/src/main/java/org/xml/sax/helpers/XMLFilterImpl.java
jre_emul/android/platform/libcore/luni/src/main/java/org/xml/sax/helpers/XMLReaderAdapter.java
jre_emul/android/platform/libcore/luni/src/main/java/org/xml/sax/helpers/XMLReaderFactory.java

Adding UnsupportedAppUsage annotation and fixed import orders to match with latest android.
Also fixed a few typos in doc.

Updating org.xml.sax, org.w3c.dom.ls and org.w3c.dom.traversal

---

jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/AbstractTCKTest.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/TCKChronoField.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/TCKChronoUnit.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/TCKIsoFields.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/TCKJulianFields.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/TCKTemporalAdjusters.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/TCKWeekFields.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/serial/TCKChronoFieldSerialization.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/serial/TCKChronoUnitSerialization.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/serial/TCKJulianFieldsSerialization.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/serial/TCKValueRangeSerialization.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/serial/TCKWeekFieldsSerialization.java

Tests are not included in build as they have to be migrated from testng to junit

Adding test for temporal tck

---

jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/AbstractTCKTest.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/TCKChronoField.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/TCKChronoUnit.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/TCKIsoFields.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/TCKJulianFields.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/TCKTemporalAdjusters.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/TCKWeekFields.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/serial/TCKChronoFieldSerialization.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/serial/TCKChronoUnitSerialization.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/serial/TCKJulianFieldsSerialization.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/serial/TCKValueRangeSerialization.java
jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/temporal/serial/TCKWeekFieldsSerialization.java
jre_emul/test_sources.mk

Test were added as is from libcore, then they were migrated from testng to junit

Adding tck test for java.time.temporal

---

jre_emul/android/platform/libcore/luni/src/test/java/libcore/java/time/format/DateTimeFormatterBuilderTest.java
jre_emul/android/platform/libcore/luni/src/test/java/libcore/java/time/format/DateTimeFormatterTest.java
jre_emul/android/platform/libcore/luni/src/test/java/libcore/java/time/format/DateTimeParseExceptionTest.java
jre_emul/test_sources.mk

DateTimeFormatterTest, DateTimeFormatterBuilderTest and DateTimeParseExceptionTest

Added test for date time formatter

---

jre_emul/Classes/java/lang/AbstractStringBuilder.m
jre_emul/android/platform/libcore/luni/src/main/java/libcore/io/IoBridge.java
jre_emul/android/platform/libcore/luni/src/main/java/libcore/io/Streams.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/io/ObjectInputStream.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/io/OutputStreamWriter.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/io/RandomAccessFile.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/lang/ArrayIndexOutOfBoundsException.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/text/MessageFormat.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/util/Arrays.java

Updated a method in ArrayIndexOutOfBoundsException and consequently updated all references to said method

Update Arrays, ArrayIndexOutOfBoundsException to latest Android source, removing hidden API.

---

jre_emul/Classes/J2ObjC_icu.m
jre_emul/android/platform/libcore/harmony-tests/src/test/java/org/apache/harmony/tests/java/util/regex/Pattern2Test.java
jre_emul/android/platform/libcore/harmony-tests/src/test/java/org/apache/harmony/tests/java/util/regex/PatternErrorTest.java
jre_emul/android/platform/libcore/luni/src/main/native/java_util_regex_Matcher.m
jre_emul/android/platform/libcore/luni/src/test/java/org/apache/harmony/regex/tests/java/util/regex/Matcher2Test.java
jre_emul/android/platform/libcore/luni/src/test/java/org/apache/harmony/regex/tests/java/util/regex/MatcherTest.java
jre_emul/android/platform/libcore/luni/src/test/java/org/apache/harmony/regex/tests/java/util/regex/ModeTest.java
jre_emul/android/platform/libcore/luni/src/test/java/org/apache/harmony/regex/tests/java/util/regex/PatternTest.java
jre_emul/android/platform/libcore/luni/src/test/java/org/apache/harmony/regex/tests/java/util/regex/ReplaceTest.java
jre_emul/android/platform/libcore/luni/src/test/java/org/apache/harmony/regex/tests/java/util/regex/SplitTest.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/util/regex/Matcher.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/util/regex/Pattern.java
jre_emul/test_sources.mk

updated source files and corresponding native code, added new test files

updating java.util.regex

---

jre_emul/JreEmulation.xcodeproj/project.pbxproj
scripts/testng2junit.py

Updating testng2junit to not use raw string for catch groups.
Updated xcode project to include new test sources.

Project maintainance

---

jre_emul/android/platform/libcore/ojluni/src/main/java/java/io/DataInput.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/io/DataInputStream.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/io/DataOutput.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/io/DataOutputStream.java

Updated DataInput.java, DataInputStream.java, DataOutput.java, and DataOutputStream.java in java.io

io Data* update

---

jre_emul/android/platform/libcore/harmony-tests/src/test/java/org/apache/harmony/tests/javax/security/auth/SubjectTest.java

Test did not use to work because of serialization issues. Now that serialization was updated, test work

Updating SubjectTest

---

jre_emul/android/platform/libcore/luni/src/test/java/libcore/java/net/DatagramSocketTest.java
jre_emul/android/platform/libcore/luni/src/test/java/libcore/java/net/ServerSocketTest.java
jre_emul/android/platform/libcore/luni/src/test/java/libcore/java/net/SocketTest.java
jre_emul/android/platform/libcore/luni/src/test/java/libcore/java/net/URLStreamHandlerFactoryTest.java
jre_emul/test_sources.mk

update java.net tests

---

jre_emul/android/platform/libcore/ojluni/src/main/java/java/io/BufferedWriter.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/io/CharArrayReader.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/io/FilterOutputStream.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/io/InterruptedIOException.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/io/PrintStream.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/io/PrintWriter.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/io/SequenceInputStream.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/io/Serializable.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/io/SerializablePermission.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/io/StringBufferInputStream.java
jre_emul/android/platform/libcore/ojluni/src/main/java/java/io/package.html

- Updated comments and copyright
- modification to lineSeparator assignment
- Use of current instance instead of WeakProxy
- modification of close() in FilterOutputStream

Updating IO

---

.gitignore
make/fat_lib_macros.mk
scripts/build_distribution.sh

Removed redundant library builds, updated distribution script, ignored generated Python scripts.
GOOGLE: N/A

Removed redundant library builds, updated distribution script, ignored generated Python scripts.

---

jre_emul/android/platform/libcore/ojluni/src/main/java/java/lang/reflect/Proxy.java
translator/src/main/java/com/google/devtools/j2objc/translate/UnsequencedExpressionRewriter.java
translator/src/main/java/com/google/devtools/j2objc/util/SourceStore.java
translator/src/test/java/com/google/devtools/j2objc/translate/UnsequencedExpressionRewriterTest.java

This fixes a few accidental imports that should have been from java.io.
Tested: `make dist` now works.

Make the ARGC branch buildable

---

.github/workflows/main.yml

Adds configuration file for GitHub Actions to build and test j2objc.

Creates GitHub Actions CI

---

jre_emul/android/platform/external/icu/android_icu4j/src/main/tests/android/icu/dev/test/format/MeasureUnitTest.java
jre_emul/android/platform/external/icu/android_icu4j/src/main/tests/android/icu/dev/test/format/PluralRulesTest.java

There is no such thing as StringBuilder(char c) regrettably.

Replacing StringBuilder(int capacity) with StringBuilder(String str).
