translator/src/main/java/com/google/devtools/j2objc/translate/OperatorRewriter.java, translator/src/test/java/com/google/devtools/j2objc/translate/OperatorRewriterTest.java
This fixes #556, that infix expressions with extended operands, such as `(1 << 2 << 3)`, are not correctly translated. In addition, two tests are added to `OperatorRewriterTest`.
=> Fix infix expression with extended operands

translator/src/main/java/com/google/devtools/j2objc/translate/ArrayRewriter.java, translator/src/test/java/com/google/devtools/j2objc/translate/ArrayRewriterTest.java
This fixes #558, that pre-/postincrement expressions containing parenthesized array accesses like `(x[0])` are mistranslated. Parenthesized expressions are now "unwrapped" first in `ArrayRewriter.needsAssignableAccess` so that the outermost prefix or postfix expression can be considered with the actual array access expression. Test cases are also added to `ArrayRewriterTest`.
One thing I noticed is that, after this fix, these two expressions will have the same translated code:
```java
x[0]++;     // (*IOSIntArray_GetRef(x, 0))++;
(x[0])++;   // (*IOSIntArray_GetRef(x, 0))++;
```
But:
```java
((x[0]))++; // ((*IOSIntArray_GetRef(x, 0)))++;
```
And this is because `ComplexExpressionExtractor` [parenthesizes an expression](https://github.com/google/j2objc/blob/f72b840c21ecf3ef8e09c36d370ba743 …
=> Fix pre/postincrement of parenthesized array access (fixes #558)

jre_emul/Classes/IOSClass.m, jre_emul/Classes/IOSConcreteClass.m, jre_emul/Tests/com/google/j2objc/ClassTest.java
This fixes #563 and bases `-[IOSClass asSubclass]` on `-[IOSClass isAssignableFrom]`. This takes away the need to implement `-asSubclass` in `IOSConcreteclass` and bring the behavior in line with other implementations ([example](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/lang/Class.java#l3266)). A test case is also supplied.
=> Use Class.isAssignableFrom to implement Class.asSubclass (fixes #563)

translator/src/main/java/com/google/devtools/j2objc/translate/ConstantBranchPruner.java, translator/src/test/java/com/google/devtools/j2objc/translate/ConstantBranchPrunerTest.java
This fixes #569, that the body of a `do` statement with constant `false` expression is erroneously skipped. A test case is also added.
=> Keep the do statement body if the const expression is false 

jre_emul/Classes/java/lang/System.java, jre_emul/Tests/java/lang/SystemTest.java, make/fat_lib.mk
This fixes #565 by providing more system properties such as `os.arch` and `os.version`. The values are selected according to the recommendations by @tomball in [this comment](https://github.com/google/j2objc/issues/565#issuecomment-119296137).
For `os.arch` I made changes to `fat_lib.mk` to pass the arch info via the `J2OBJC_BUILD_ARCH`. I'm not completely sure how the Makefile interacts with the Xcode project, and please let me know if I updated `FAT_LIB_XCODE_FLAGS` correctly, or if there are other places I also need to update.
For `os.version`, I decided to use the new `[NSProcessInfo processInfo].operatingSystemVersion` API before falling back to other means. I decided not to use the deprecated [Gestalt Manager](https://developer.apple.com/library/mac/documentation/Carbon/Reference/Ges …
=> Provide more system properties, such as os.arch (fixes #565)

jre_emul/Classes/JavaMetadata.m
This adds `autorelease` to three allocation sites in `JavaMetadata`. I found `-allFields` was leaking `JavaFieldMetadata` instances, and thought other two places also needed `autorelease`.
=> Fix memory leaks in JavaMetadata

jre_emul/Classes/J2ObjC_source.h, jre_emul/Tests/com/google/j2objc/AssertTest.java, jre_emul/tests.mk, translator/src/main/java/com/google/devtools/j2objc/gen/StatementGenerator.java, translator/src/test/java/com/google/devtools/j2objc/gen/StatementGeneratorTest.java, translator/src/test/java/com/google/devtools/j2objc/translate/AutoboxerTest.java, translator/src/test/java/com/google/devtools/j2objc/translate/UnsequencedExpressionRewriterTest.java
This fixes #590 by using macro to implement `JreAssert`. A new test case is also added and has been run first without then with the change.
=> Implement JreAssert with macro so that msg is conditionally evaluated

translator/src/main/java/com/google/devtools/j2objc/pipeline/TranslationProcessor.java, translator/src/main/java/com/google/devtools/j2objc/translate/DeadCodeEliminator.java, translator/src/main/java/com/google/devtools/j2objc/translate/InitializationNormalizer.java, translator/src/main/java/com/google/devtools/j2objc/util/DeadCodeMap.java, translator/src/test/java/com/google/devtools/j2objc/translate/DeadCodeEliminatorTest.java, translator/src/test/java/com/google/devtools/j2objc/translate/InitializationNormalizerTest.java
This fixes the cases discussed in #599 with changes to `DeadCodeEliminator`. This requires that the dead code map be passed to `InitializationNormalizer` later in the translation process, though. I've also added the discussed test cases. Improvements include:
* Don't remove static nested classes from a dead class
* Also visit static nested classes in a dead class
* Be more strict about what makes a value inlinable
* Don't call super from the generated default constructor if the entire class is dead or if all constructors are dead
=> Improve dead code elimination

jre_emul/Classes/java/lang/Throwable.m
This fixes the leaks in `Throwable` (#601). Currently the only place where `suppressedExceptions` is released is when `-[Throwable addSuppressedWithJavaLangThrowable:]` is called. I wasn't sure if `suppressedExceptions` is used/handled elsewhere, but in jre_emul `suppressedExceptions` only appears in `Throwable.m`, so I thought this should be released in `-dealloc`.
=> Fix memory leaks in Throwable

jre_emul/android/libcore/luni/src/main/java/java/nio/FileChannelImpl.java, jre_emul/android/libcore/luni/src/main/java/java/nio/channels/FileLock.java
This fixes the leaks in `FileChannelImpl` and `FileLock` as discussed in #603 .
=> Fix FileChannelImpl and FileLock memory leaks

jre_emul/android/libcore/luni/src/main/java/java/io/Reader.java, jre_emul/android/libcore/luni/src/main/java/java/io/Writer.java, jre_emul/android/libcore/luni/src/main/java/java/util/Collections.java
This fixes #605 following @tomball's suggestion that we can just use a new object for the lock.
I'm a little curious what happens when j2objc wants to merge the next version of Android source. Would this kind of fix cause future maintenance issues?
=> Fix the "lock = this" pattern in Reader, Writer, and synchronized Collections

jre_emul/android/libcore/luni/src/main/java/java/util/concurrent/FutureTask.java
If a FutureTask is already running when it is canceled by another thread, the Callable in the FutureTask is released immediately and the Callable.call method can crash it it references `this`. This fix makes sure the FutureTask keeps a local retained reference to the Callable while it runs.
Fixes issue #622 (ThreadPoolExecutor releases tasks prematurely when interrupted).
=> Fix premature release in canceled FutureTask

docs/Memory-Model.md
In the future, keeping lines < 100 columns will make the diffs easier to review.
=> Small edits to Memory Model page.

jre_emul/Classes/java/lang/StackTraceElement.java
Swift frames are currently excluded from stack traces (e.g. when logging exceptions and via `Thread.getStackTrace()`) because Swift mangles symbol names. This patch adds native code in StackTraceElement.java to attempt to demangle the most common forms of Swift function symbols so that they appear in j2obc-generated stack traces.
As far as I know, the name mangling scheme is undocumented. This implementation uses info from several sources online where people have reverse-engineered the format, as well as some of my own experimentation. It doesn't handle every possible Swift symbol, but it should handle most "normal" object methods, and it should bail out safely if it encounters anything that it doesn't recognize.
It would be nice to have tests for this, but I haven't figured out how to …
=> Swift frames in stack traces

jre_emul/stub_classes/java/lang/Number.java
Hi,
Sorry in advance for my poor english.
I've an error when I translate a class at who I pass a "Long" type when it expect a generic type serializable and comparable:
error: SimpleAutoIndexedEntity.java:15: Bound mismatch: The type Long is not a valid substitute for the bounded parameter <ID extends Serializable & Comparable<ID>> of the type SimpleEntity<ID>
It seems that it was because the Number.java (who is present in the jre_emul.jar file) doesn't implement java.io.Serializable. That's why "Long" class who inherit of the "Number" class can't be serializable.
I've compared to the official Number.java file from the java.lang package and there is other differences on byteValue and shortValue methods.
I don't know if it's necessary, or obligatory, to update this methods too, but this …
=> Update Number.java for Long serializable

translator/src/main/java/com/google/devtools/j2objc/translate/DeadCodeEliminator.java, translator/src/main/java/com/google/devtools/j2objc/util/BindingUtil.java, translator/src/test/java/com/google/devtools/j2objc/translate/DeadCodeEliminatorTest.java
This fixes #654 by adding a new `getProGuardSignature` method to `BindingUtil` so that the dead code eliminator can use the correct signature to match against the dead code report. As mentioned in #654, the signature was not correct because dead code elimination is the first pass in the translation processor, before inner class methods are furnished with outer types in a later pass.
Since `InitializationNormalizer` needs the dead code map to work correctly, I wonder if dead code elimination should be done after `InnerClassExtractor` is finished, but I'm not sure if the pass will still work after the nodes have been modified by the other passes. The downside of the approach here is one more special case in `BindingUtil`, though I believe it's straightforward enough for the job.
This also …
=> Eliminate inner class constructors correctly when ProGuard explicitly instructs so

doc/man/j2objc.1, translator/src/main/java/com/google/devtools/j2objc/Options.java, translator/src/main/resources/com/google/devtools/j2objc/J2ObjC.properties, translator/src/test/java/com/google/devtools/j2objc/gen/ObjectiveCSegmentedHeaderGeneratorTest.java
Adds the flag --no-segmented-headers to disable the feature.
Ignore and accept the old --segmented-headers flag.
Per https://groups.google.com/d/msg/j2objc-discuss/Db3YUD9V0TY/C4HYerpQAwAJ
=> Segmented-headers defaults to true

.travis.yml, scripts/osx-set-java.sh
The Travis CI jobs of my fork was reporting the following errors: [this job](https://travis-ci.org/lukhnos/j2objc/jobs/95389403) failed because Travis CI's default OS X image was still on Xcode 6.1, then after upgrading the setting [this job](https://travis-ci.org/lukhnos/j2objc/jobs/95399149) failed because it appears that `brew-cask` has now been part of the recent OS X images.
After those changes it now builds, but [this job](https://travis-ci.org/lukhnos/j2objc/jobs/95404176) didn't finish because it exceeded the maximum 50 minutes that Travis allows. Perhaps we could disable `make dist` for now and only run the tests?
=> Upgrade Travis CI settings

jre_emul/android/libcore/luni/src/main/java/java/lang/ref/ReferenceQueue.java
This fixes #675 by using a sentinel object to mark that a `Reference` is the only entry in the queue. I followed @kstanger's [previous fix for ConcurrentLinkedQueue](https://github.com/google/j2objc/commit/db2597b64e3cd8ce18a6d8832df08b35a7a7b529) for the naming convention.
After this I no longer see the leaks in [my test case](https://gist.github.com/lukhnos/f628a45939cba16d3f11), and an app of mine that uses a lot of `WeakHashMap` no longer leaks.
One thing I don't fully understand is under which condition a `ReferenceQueue` may still have entries not removed by `poll()` (and therefore it leaves to the translated queue's `-dealloc` to clean up the `head`) , but I'm definitely interested in using this chance to learn more about J2ObjC's weak-referencing mechanism.
=> Fix cyclic reference leaks in ReferenceQueue

jre_emul/android/libcore/luni/src/main/java/java/lang/ClassLoader.java
This implements #678. Previously `ClassLoader.findResources` finds resource in `[NSBundle allBundles]`, which are non-framework bundles. With `[NSBundle allFrameworks]` we enable the use of dynamic frameworks.
One caveat though is that this now searches many more bundles. If we log the method, it'll look something like this:
```
finding: some/resource/path/file.ext
searching in non-framework bundle: org.lukhnos.MyApp
searching in non-framework bundle: com.apple.uikit.Artwork
searching in framework bundle: com.apple.Foundation
searching in framework bundle: com.apple.AddressBook
searching in framework bundle: com.apple.iphonesimulator.SimulatorClient
searching in framework bundle: (null)
searching in framework bundle: com.apple.BackBoardServices
searching in framework bundle: …
```
=> Search for resource in [NSBundle allFrameworks]

jre_emul/Classes/NSException+JavaThrowable.m
Simple fix for the Throwable constructor defined in `NSException+JavaThrowable.m` leaking the suppressedExceptions array.
=> Fix a memory leak in Throwable constructor

make/common.mk, make/fat_lib_macros.mk, scripts/sysroot_path.sh
This PR introduces support for tvOS (Apple TV):
* Two new architectures are added in the J2OBJC_ARCHS: appletvos and appletvsimulator.
* A new output dir. is added, to contain binaries for tvOS builds. This dir. is handled similarly to the OS X case.
Additionally, this PR sets a target for OS X to 10.7, roughly equivalent (in terms of APIs) to the iOS 5.0 target already in place.
Changes have been tested and we are currently using the tvOS binaries with no issues so far.
=> Apple TV support +  OS X target to 10.7

translator/src/main/java/com/google/devtools/j2objc/gen/StatementGenerator.java, translator/src/test/java/com/google/devtools/j2objc/gen/StatementGeneratorTest.java
Currently a multi-catch statement like:
catch (A | B e) {}
is translated to _three_ objc `@catch` clauses:
@catch (A *e) {}
@catch (B *e) {}
@catch (JavaLangRuntimeException *e) {}
The last `@catch` clause seems to be the closest common ancestor of `A` and `B`, but from what I understand, this doesn't match the semantics of the Java multi-catch syntax. In fact, if the multi-catch is followed by a `catch (C e) {}`, where `C` also inherits `RuntimeException`, the translated `@catch (C *e)` clause is never reached because it is shadowed by the extraneous `@catch` clause.
This pull request changes the translation to omit the extra `@catch` clause after a multi-catch. Please review because I can't help but think that the extra `@catch` clause was previously being generated intentionally.
=> Don't catch a generic Exception following a multi-catch statement

jre_emul/Classes/com/google/j2objc/net/IosHttpURLConnection.java, jre_emul/Classes/com/google/j2objc/net/IosHttpsURLConnection.java, jre_emul/Classes/com/google/j2objc/security/cert/IosCertificateFactory.java, jre_emul/Classes/com/google/j2objc/security/cert/IosX509Certificate.java, jre_emul/android/platform/libcore/luni/src/test/java/libcore/java/net/URLConnectionTest.java, jre_emul/misc-tests/InspectSSLAfterConnect.java
I implemented NSURLSessionDelegate's NSURLAuthenticationChallenge delegate to get the
raw DER data.
Then java.security.cert.CertificateFactory generates the
required (X509)Certificate[].
Apache harmony's Certificate types and ASN.1 DER parser are used in the
underlying implementation of IosX509Certificate to get the fields
contained in the certificate.
The #verify methods aren't implemented yet. Baby steps.
My aim was to do full certificate and public key pinning, with the same codebase.
=> Implementation of getServerCertificates for HttpsURLConnection

jre_emul/Classes/com/google/j2objc/net/IosHttpURLConnection.java
This fixes a bug where `HttpUrlConnection.getHeaderField(String)` was comparing keys in a case-sensitive way. I didn't see any existing tests for this class so I got lazy about creating one for this small fix.
=> HttpURLConnection.getHeaderField() should be case-insensitive

translator/src/main/java/com/google/devtools/j2objc/translate/AbstractMethodRewriter.java, translator/src/test/java/com/google/devtools/j2objc/translate/AbstractMethodRewriterTest.java
If a superclass contains a method that returns a parameterized type, a subclass that narrows that type shouldn't include a declaration of that method in the .m file if it is a private method since the subclass is restricted from calling that method. In practice, this was causing compilation errors if the method argument list contained types that are not already imported in the subclass.
This patch fixes the issue and includes a test case.
=> Don't redeclare generic private method in subclass

_posts/2017-01-30-retain-cycles.md
I used the `excerpt` field to the front matter so that Jekyll does not use the first paragraph as the default excerpt. It now reads:
> In this blog post, we'll talk about how you can break retain cycles in your Java code. We will cover the @Weak and @WeakOuter annotations as well as a few additional tools and techniques you can use.
=> Blog about breaking retain cycles

jre_emul/Classes/com/google/j2objc/net/IosHttpURLConnection.java
NSURLSession has a response cache that is on by default. This change disables the
cache when HttpURLConnection.useCaches is false.
This pull came about from a need to stop http responses being written to device storage
for security reasons.
=> IosHttpURLConnection - stop NSURLSession caching to disk when useCaches is false     

jre_emul/Classes/com/google/j2objc/net/IosHttpURLConnection.java
IosHttpURLConnection currently does not validate SSL certificates.
This change updates the URLSession didReceiveChallenge delegate method
to complete with NSURLSessionAuthChallengePerformDefaultHandling to
allow iOS to handle TLS challenge.
=> Fix for IosHttpURLConnection not validating SSL certificates

jre_emul/android/frameworks/base/core/java/android/os/SystemClock.java
As an Android developer I was very happy to use `SystemClock` in the shared code for a media playing app which heavily relies on timers. Unfortunately I ran into the following issues:
* The iOS implementation of `elapsedRealtime()` is not monotonic, as the used `systemUptime` does not take sleep time into account.
The issue was hard to find, since it works in many cases and I was blind, knowing the contract of the Android's API ;)
* `elapsedRealtimeNanos()` returns the same value during the lifetime of a process, since it only returns the actual boot time of the system. But as the SO post below describes, even this fixed time can change, if the user/system changes the OS time.
The implementation of `elapsedRealtimeNanos()` actually has another issue: the returned value contains a …
=> Fixed several issues of SystemClock.

jre_emul/android/platform/libcore/ojluni/src/main/java/java/lang/Throwable.java
The new implementation of `Throwable` in the 2.0.2 release has a retain cycle when initialized without a `cause` because the `cause` instance variable is set to `this`. This changes it to reference a sentinel value instead.
=> Fix a self-retain cycle in Throwable in 2.0.2

jre_emul/Classes/com/google/j2objc/security/IosRSAKey.java, jre_emul/Classes/com/google/j2objc/security/IosRSAKeyFactory.java, jre_emul/Classes/com/google/j2objc/security/IosRSAKeyPairGenerator.java, jre_emul/Classes/com/google/j2objc/security/IosRSASignature.java
a) generating KeyPairs with different keys
Our requirements are to genereate KeyPairs for several users. I noticed
that the created KeyPairs created had all the same identical keys.
To solve this problem, in method generateKeyPair, I first deleted any
existing public/private keys. Then the keys were always created new.
see Class IosRSAKeyPairGenerator.java
b)RSA Sign padding
When RSASignature nativeEngineSign signs the message always with
"kSecPaddingNone" but the nativeEngineVerify method use PKCS1.
The output of the "sign" message is not comapatile with PKCS1. So I
changed RSASignature so that the method nativeEngineSign will also use
PKCS1 padding.
See class IosRSASignature.java
c) engineGeneratePrivate
The KeySpec for PrivateKey generation is PKCS8EncodedKeySpec. The method …
=> RSA improvements

jre_emul/android/platform/libcore/luni/src/main/java/java/util/concurrent/ConcurrentSkipListMap.java
- The self references in the marker nodes are leaking
- as recommended, implement a sentinel instead
closes #946 
cc: @AlexandreHetu
=> ConcurrentSkipListMap: Use sentinel instead of self references

jre_emul/android/platform/libcore/luni/src/main/java/java/util/concurrent/ConcurrentSkipListMap.java
Reverts google/j2objc#947: ConcurrentSkipListMapTest unit test fails with null pointer exception:
```
java.lang.NullPointerException
at 0x000000010f705ea8 java.lang.Throwable.nativeFillInStackTrace() + 24
at 0x000000010f6cdd05 java.lang.Exception.<init>() + 21
at 0x000000010f6e5c15 java.lang.RuntimeException.<init>() + 21
at 0x000000010f6e1b55 java.lang.NullPointerException.<init>() + 21
at 0x000000010f289167 java.util.concurrent.ConcurrentSkipListMap.doRemove() + 39
at 0x000000010f28b968 java.util.concurrent.ConcurrentSkipListMap.remove() + 40
at 0x000000010f296a8f java.util.concurrent.ConcurrentSkipListMap$SubMap.clear() + 271
at 0x000000010e9422fb jsr166.ConcurrentSkipListSubMapTest.testClear() + 75
```
=> Revert "ConcurrentSkipListMap: Use sentinel instead of self references"

make/common.mk, make/fat_lib_macros.mk, scripts/sysroot_path.sh
Now (before changes from this PR) iOS jre_emul static library is still built with armv7k architecture. This slice should be a part of a separate watchOS jre_emul library that should also contain slice for watchsimulator sdk. Just like it has been done for tvOS.
=> Add watchOS simulator support

jre_emul/Classes/IOSClass.m
Hi team,
I found one issue, failure of Class.forName() for a class has package prefix.
I investigated this and finally I could find the root cause.
That is, IOSClass_initialize() is not called at the top of the static methods of java.lang.Class (IOSClass).
I guess IOSClass_initialize() should be called, because other translated code includes such code.
Could you please review this ?
I created two commits. The one is to reproduce the issue, and the other one is the fix.
=> IOSClass initialize issue

translator/src/main/java/com/google/devtools/j2objc/translate/Autoboxer.java, translator/src/test/java/com/google/devtools/j2objc/translate/AutoboxerTest.java
Casting java.lang.Character to a primitive currently attempts to cast it directly into its boxed type (as is done with Object types), which will fail in runtime and is inconsistent with java.
According to the JLS:
"Assignment contexts allow the use of ... an unboxing conversion optionally followed by a widening primitive conversion"
Character is the only source for such Unboxing+widening conversions that is not a Number, and it converts to int, long, float and double.
This commit adds a special casing for Character, on top of the existning case for Number conversions.
=> Add support for Character unboxing on cast

annotations/pom.xml
There are many Java libraries licensed under "Apache License, Version 2.0" that do not use its official spelling.
This causes issues like https://issues.apache.org/jira/browse/MPIR-382: with every library defining its own spelling, it's difficult in large projects to have a clear view of all licenses in use.
This PR changes the license spelling to the official one, as advised by Maven developers.
=> Fix "Apache License, Version 2.0" spelling

README.md
a very small typo. IOS -> iOS.
=> Fix a very small typo

BUILD.dist, WORKSPACE.dist, examples/Contacts/BUILD.bazel
This change is required before flipping --incompatible_load_java_rules_from_bzl in Bazel (see bazelbuild/bazel#8746)
=> Load the java rules from @rules_java repository.

jre_emul/java.mk, make/common.mk, xalan/Makefile
Fixes this problem when building j2objc on a Mac:
```
Building libxalan.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo -create /Users/matt.fluet/repo/cross-platform/j2objc/xalan/build_result/objs-appletvos/libxalan.a /Users/matt.fluet/repo/cross-platform/j2objc/xalan/build_result/objs-appletvsimulator/libxalan.a -output /Users/matt.fluet/repo/cross-platform/j2objc/xalan/build_result/appletvos/libxalan.a
building j2objc_xalan.jar
mktemp: too few X's in template ‘j2objc-xalan’
```
=> Fix jar template issue in xalan build

translator/src/main/resources/com/google/devtools/j2objc/reserved_names.txt
Xcode 11's SDKs updated /usr/include/time.h with a "timezone" #define, so it needs to be added to j2objc's reserved words list.
=> Added "timezone" reserved word from /usr/include/time.h.

jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/format/TCKDateTimeFormatter.java, jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/format/TCKDateTimeFormatterBuilder.java, jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/format/TCKDateTimeFormatters.java, jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/format/TCKDateTimeParseResolver.java, jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/format/TCKDateTimeTextPrinting.java, jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/format/TCKDecimalStyle.java, jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/format/TCKFormatStyle.java, jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/format/TCKInstantPrinterParser.java, jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/format/TCKLocalizedFieldParser.java, jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/format/TCKLocalizedFieldPrinter.java, jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/format/TCKOffsetPrinterParser.java, jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/format/TCKPadPrinterParser.java, jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/format/TCKResolverStyle.java, jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/format/TCKSignStyle.java, jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/format/TCKTextStyle.java, jre_emul/android/platform/libcore/ojluni/src/test/java/time/tck/java/time/format/TCKZoneIdPrinterParser.java
Removing empty line between doc-comment and annotation
Comment each test case on an individual basis. 
Before one comment was being used to comment out consecutive tests that used calendars different from julian or gregorian. Now individual comments are used to make more clear the intended behavior.
=> Reformatting time.format.tests

jre_emul/Classes/dalvik/system/VMStack.java, jre_emul/jre_sources.mk
Updated VMStack to function closely to current android version These methods were changed the most: getStackClass2(), getThreadeStackTrace(), fillStackTraceElements(). This implementation was chosen due to repeated call of these methods in the current version of android.
=> updated VMStack to function closely to current android version.

jre_emul/android/platform/libcore/ojluni/src/main/java/sun/reflect/Reflection.java
reverted getCallerClass() to refly on VMStack to avoid repeated code and minimize differences between J2ObjC and android
=> updated reflection.java

make/common.mk, make/fat_lib_macros.mk
Verified with:
```
> lipo -archs jre_emul/build_result/macosx/libjre_emul.a 
x86_64 arm64
```
Is anything else needed?
=> Add support for the arm64 architecture for macOS

make/common.mk, make/fat_lib_macros.mk, make/framework.mk
- Fixing building on M1 Mac (one note here, protobuf 3.11.1 doesn't exist for arm64, I used the latest in brew 3.15.8)
- Adding arm64 simulator
- Removing i386 simulator. Due to the way xcframeworks are built I renamed x86_64 to simulator and arm64 to simulator64. Alternatively you could keep them all and always build i386 as well.
=> M1 support

make/common.mk, make/fat_lib_macros.mk, make/framework.mk, scripts/gen_xcframework.sh
This PR addresses some issues during the construction of the xcframework.
**Thin vs fat libraries**
When building the xcframework for each platform an own fat library has to be used. But for iphone, simulator, watchos, watchsimulator for each slice a thin library was used. That caused `xcodebuild -create-xcframework` complains with 
'Both x and y represent two equivalent library definitions.'
There was a workaround in `gen_xcframework` which just skipped the archs `iphone64e` and `watchv7k` and so they are also missing in the xcarchive. `watchv7k`is still required to upload a watchos app to app store.
**Missing archs**
For WatchOS the arches `x86_64` and `arm64` are not built. These are required to be able to run a WatchOS 6 or later app in a simulator. So current app watch apps are only …
=> Fix construction of xcframework architectures

annotations/pom.xml
org.sonatype.oss:oss-parent:7 is unsigned (missing .asc files), which forces users of j2objc-annotations library
that enforce signature verification to explicitly allowlist oss-parent. Luckily oss-parent 9 is signed,
thus fixing this issue.
See:
https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/7/
vs
https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/
=> Upgrade to oss-parent 9

README.md
J2ObjC no longer builds with JDK 1.8. See Issue #2115 for details.
=> Removed "JDK 1.8" from the "Requirements" section of the "README.md" file

make/framework.mk
When building XCFramework artefacts, don't create Versions folder with Headers symlink; create real Headers folder instead
=> Change XCFramework artefact format to keep Xcode 15 happy

make/framework.mk, scripts/gen_xcframework.sh
Updated the `make/framework.mk` and `scripts/gen_xcframework.sh` files so that the `xcodebuild -create-xcframework` command is called with the `-headers` option. Fixes #2180.
=> Now calling the `xcodebuild -create-xcframework` command with the `-headers` option

make/framework.mk
Changed the `make/framework.mk` file so that the name of the module in the generated `module.modulemap` file corresponds to the module being built. Fixes #2111.
=> Fixed the module names in the `module.modulemap` files

make/framework.mk
Changed the `framework.mk` file so that it no longer makes the `module.modulemap` file as part of its execution. In summary, the `module.modulemap` file does not serve a purpose within XCFrameworks which bundle up a set of static libraries. See the discussion in Issue #2185 for more detailed rationale. This change fixes issue #2185.
=> Removed the `module.modulemap` file from the XCFrameworks

make/framework.mk
Changed some places in `make/framework.mk` where a target was referring to itself by name to use the `$@` notation instead.
=> Minor tidy-up in the `make/framework.mk` file

jre_emul/android/platform/libcore/ojluni/src/main/java/java/nio/DirectByteBuffer.java
This is another memory-leak that happens within my setup using the java.nio.* implementation. Just like shown in https://github.com/google/j2objc/issues/2501 it creates cyclic reference between the `DirectByteBuffer` and `MemoryRef`. 
Since the mechanism was created to hold a reference to the original Buffer, after the "live" reference might has been deallocated, this seems not to be a working mechanism in Objective-C.
This change sets the originalBufferObject to always null (like on the other constructor already) to avoid this behavior.
Therefore now the MemoryRef loses its functionality of keeping the DirectByteBuffer's ref. I could not find any negative effects tough, since I am convinced, this can not happen in the transpiled framework anyways.
=> Setting Null-Reference on for originalBufferObject on MemoryRef
